### ISSUE TITLE
Update prevents VLAN0?

### ISSUE THREAD

**Issue by cinderblock** [jaysoffian/eap_proxy#52]
I'm trying to be bug an issue that just happened. I updated my controller software and now my internet that has been so reliable doesn't work.

I suspect the controller update included a firmware update to the USG because internet died shortly after it updated. Or it could have been a reprovision. Or it could have just been a restart.

Anyway, now I'm in my USG, and `ifconfig` doesn't show a second VLAN for `eth0`, my WAN device.

Running `eap_proxy.py`, I get errors:

```log

root@router:~# /usr/bin/python /config/scripts/eap_proxy.py eth0 eth2 --restart-dhcp --ignore-when-wan-up --ignore-logoff --ping-gateway --set-mac --vlan-id 0 --pidfile /var/run/eap_proxy.pid --debug-packets
[2022-11-30 18:25:43,982]: starting proxy_loop
[2022-11-30 18:25:47,176]: eth2: recv 60 bytes:
0x0000:  0180 c200 0003 8c5a 25db 5131 888e 0201
0x0010:  0000 0000 0000 0000 0000 0000 0000 0000
0x0020:  0000 0000 0000 0000 0000 0000 0000 0000
0x0030:  0000 0000 0000 0000 0000 0000
[2022-11-30 18:25:47,179]: eth2: 8c:5a:25:db:51:31 > 01:80:c2:00:00:03, EAPOL start (1) v2, len 0
Traceback (most recent call last):
  File "/config/scripts/eap_proxy.py", line 869, in <module>
    sys.exit(main())
  File "/config/scripts/eap_proxy.py", line 865, in main
    return proxy(args, log)
  File "/config/scripts/eap_proxy.py", line 817, in proxy_loop
    proxy.proxy_loop()
  File "/config/scripts/eap_proxy.py", line 602, in proxy_loop
    self.on_poll_event(socks[fd], event)
  File "/config/scripts/eap_proxy.py", line 623, in on_poll_event
    self.on_router_eap(eap)
  File "/config/scripts/eap_proxy.py", line 651, in on_router_eap
    if self.os.getmac(if_vlan) == eap.src:
  File "/config/scripts/eap_proxy.py", line 478, in getmac
    return getifhwaddr(ifname)
  File "/config/scripts/eap_proxy.py", line 180, in getifhwaddr
    with open("/sys/class/net/%s/address" % ifname) as f:
IOError: [Errno 2] No such file or directory: '/sys/class/net/eth0.0/address'
```

Looks like the vlan isn't getting set for some reason. Any ideas?

**Comment by cinderblock** [comment]
Looking into this more, VLAN 0 is being created... So that may not be it.

I managed to get it to connect once, but I killed the proxy binary and then something else reset and I haven't managed to get it back.

Playing with code trying to see how far it's getting, it doesn't seem to get past this `poll.poll()`:
https://github.com/jaysoffian/eap_proxy/blob/78a058ffe67c253da5153d82a3a729588966f02e/eap_proxy.py

I'm not super familiar with python put I'll try to dig into this some more

**Comment by cinderblock** [comment]
Restarting the ONT seems to have gotten the polling to run. Maybe it was just waiting for events the whole time. It's still not 100% clear to what what has broken here, or why those events would have stopped coming in.

**Comment by cinderblock** [comment]
Well, in the end, it looks like it was a confluence of things. Posting here in case this helps someone in the future, but this doesn't seem to have been an `eap_proxy` issue.

1. Unifi seems to be pushing to not allow VLAN 0 directly. There seems to be some conflict with QoS tags or something. I'm not super familiar with this low level ethernet functionality. Maybe I'll read some more and update this comment.
2. AT&T seems to have added some restrictions - if you try talking to them without securing the connection first or on the wrong VLAN, they stop trying to reconnect until you cycle the physical link. I think this is why I thought `eap_proxy` was hanging - AT&T was just not starting the authentication process.
3. The not working uplink meant many client devices would self disconnect from the WiFi to use GSM, then get back onto WiFi with a new generated MAC address, and the local DHCP pool was exhausted, making me think something more significant had changed/broken on the USG.
